#! /usr/bin/bash
# This script opens the log of a running container when used with a container name.
# Example command to use this script: 
# ./log frontend 
# This will open the log of the running frontend container. 

if [ $# -ne 1 ]
then
    echo "Container name: $($1)"
    exit 1
fi

container_name="$1"
CONTAINER_NAME=$(docker container ls --all --quiet --filter "name=$container_name")
docker logs --tail 1000 -f $CONTAINER_NAME
